# Global options
generatorOptions:
  disableNameSuffixHash: true
  labels:
    grafana_dashboard: "1"
commonAnnotations:
  grafana_folder: "Kubernetes"
#namespace: monitoring

# Generate a ConfigMap for each dashboard
configMapGenerator:

#################################################
# Views Dashboards
#################################################

- name: dashboards-k8s-views-global
  files: [ dashboards/k8s-views-global.json ]

- name: dashboards-k8s-views-namespaces
  files: [ dashboards/k8s-views-namespaces.json ]

- name: dashboards-k8s-views-nodes
  files: [ dashboards/k8s-views-nodes.json ]

- name: dashboards-k8s-views-pods
  files: [ dashboards/k8s-views-pods.json ]

#################################################
# System / Addons Dashboards
#################################################

- name: dashboards-k8s-system-api-server
  files: [ dashboards/k8s-system-api-server.json ]

- name: dashboards-k8s-system-coredns
  files: [ dashboards/k8s-system-coredns.json ]

#################################################
# Shared Services / Addons Dashboards
#################################################

- name: cilium-dashboard
  files: [ dashboards/cilium.json ]

- name: hubble-dashboard
  files: [ dashboards/hubble.json ]

- name: hubble-l7-http-dashboard
  files: [ dashboards/hubble-l7-http-metrics.json ]

- name: minio-dashboard
  files: [ dashboards/minio.json ]

- name: traefik-dashboard
  files: [ dashboards/traefik.json ]

- name: keycloak-dashboard
  files: [ dashboards/keycloak.json ]

- name: mysql-exporter-dashboard
  files: [ dashboards/mysql-exporter.json ]

- name: mongodb-exporter-dashboard
  files: [ dashboards/mongodb-exporter.json ]
  
- name: es-exporter-dashboard
  files: [ dashboards/es-exporter.json ]

# grafana tempo dashboard not imported

# grafana alloy dashboard not imported
  
# grafana loki dashboard imported via helm chart definition
  
- name: grafana-dashboard
  files: [ dashboards/grafana.json ]


- name: postgresql-dashboard
  files: [ dashboards/postgresql.json ]
  
- name: coder-dashboard
  files: [ dashboards/coder.json ]
  
# strimzi dashboards imported via operator helm chart

- name: vault-dashboard
  files: [ dashboards/vault.json ]

- name: argo-workflow-dashboard
  files: [ dashboards/argo-workflow.json ]

- name: k8up-dashboard
  files: [ dashboards/k8up.json ]

- name: sonarqube-dashboard
  files: [ dashboards/sonarqube.json ]

- name: rabbitmq-overview-dashboard
  files: [ dashboards/rabbitmq-overview.json ]  
  
- name: teleport-dashboard
  files: [ dashboards/teleport.json ]    