# Global options
generatorOptions:
  disableNameSuffixHash: true
  labels:
    grafana_dashboard: "true"
commonAnnotations:
  grafana_folder: "Kubernetes"
#namespace: monitoring

# Generate a ConfigMap for each dashboard
configMapGenerator:

#################################################
# Views Dashboards
#################################################

- name: dashboards-k8s-views-global
  files: [ dashboards/k8s-views-global.json ]

- name: dashboards-k8s-views-namespaces
  files: [ dashboards/k8s-views-namespaces.json ]

- name: dashboards-k8s-views-nodes
  files: [ dashboards/k8s-views-nodes.json ]

- name: dashboards-k8s-views-pods
  files: [ dashboards/k8s-views-pods.json ]

#################################################
# System / Addons Dashboards
#################################################

- name: dashboards-k8s-system-api-server
  files: [ dashboards/k8s-system-api-server.json ]

- name: dashboards-k8s-system-coredns
  files: [ dashboards/k8s-system-coredns.json ]

- name: dashboards-k8s-addons-starboard-operator
  files: [ dashboards/k8s-addons-starboard-operator.json ]

#################################################
# Custom Dashboards
#################################################

- name: dashboards-argocd-all
  files: [ dashboards/argocd-full.json ]

- name: dashboards-argo-workflow-all
  files: [ dashboards/argoworkflow-full.json ]

- name: dashboards-ambassador-all
  files: [ dashboards/ambassador-full.json ]

- name: dashboards-keycloak-all
  files: [ dashboards/keycloak-full.json ]

- name: dashboards-minio-all
  files: [ dashboards/minio-full.json ]
  
- name: dashboards-traefik-all
  files: [ dashboards/traefik-full.json ]
